### ISSUE TITLE
Make 'node-proxy' an optionalDependency

### ISSUE THREAD

**Issue by natevw** [natevw/fermata#40]
That way users can decide whether to stick to parentheses, start their app with the right V8 flags, or require it themselves.

This would also facilitate use on certain platforms that offer the standard modules of node.js but are not actually powered by V8.

**Comment by mik01aj** [comment]
+1. Plus, requiring node-proxy breaks the build for those using browserify.

**Comment by natevw** [comment]
I've actually got this in place on a somewhat-unstable "upcoming" branch (`npm install git://github.com/natevw/fermata.git#upcoming` or use `…fermata.git#<current_hash>` for stability) if you want to give it a shot. (The main instability on that branch would be around the new streaming response type and [how it will be exposed](https://github.com/natevw/fermata/issues/51).)

It's tempting to move it to something like [peerDependencies](https://github.com/npm/npm/issues/1400) [although I think that's something different] or just document it as an optional "install it yourself" — I'm guessing it won't be long before v8 provides Proxy object itself by default (if not already in io.js) and due to its still pending in-browser status I find I don't really use the dot syntax anyway so it's just extra time spent building every deploy…

**Comment by laktak** [comment]
+1

**Comment by natevw** [comment]
This is done in `fermata@0.11.0-beta1`, specifically https://github.com/natevw/fermata/commit/173def0b82d244f2892ff93473256544b07260e5
