### ISSUE TITLE
fermata.js:78 Uncaught TypeError: Proxy.createFunction is not a function

### ISSUE THREAD

**Issue by shyamchandranmec** [natevw/fermata#57]
Hi, 
I am using fermata to make rest calls. Now I am getting the error mentioned in the title.  Given below is the sample code which I am using

```
var site = fermata.json("")(['restaurants']).post(restaurantDetails, function (err, resp) {
                console.log("done")

            })
```
I am using fermata version 0.10.1
I am getting this error in chrome version in OSX - Version 49.0.2623.87 (64-bit)
This was working fine last month in chrome. I don't know the version I used.
Its working fine in Friefox in OSX.

**Comment by natevw** [comment]
Sorry about that, first got wind of this a few days ago when this was still in Chrome Canary but hadn't tackled it yet :-/

What happened is that Chrome must have gotten rid of some earlier "Harmony Proxies" behavior that changed in the final spec. Should be fixed now in `fermata@0.10.8`.

Thanks for the bug report!

**Comment by shyamchandranmec** [comment]
@natevw  Thanks for the quick reply. I will download that version

**Comment by shyamchandranmec** [comment]
@natevw  Can you tag it as 0.10.8. I am not able to update via bower
